### ISSUE TITLE
Double services.AddMetricFactory() call

### ISSUE THREAD

**Issue by Zagrebelin** [prom-client-net/prom-examples#120]
[There is](https://github.com/prom-client-net/prom-examples/blob/dbd68b03a0c6a13b1b6c67904348fee9a42f3e3e/src/WebHttpRequestDurations_3.1/Startup.cs#L26) a double call of .AddMetricFactory() method in the WebHttpRequestDurations_3.1 exmample project.

Is it a mistake or intentional behavior?

```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMetricFactory();
            services.AddControllers();
            services.AddMetricFactory();
        }
```

**Comment by phnx47** [comment]
Fixed this line
